// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zeigarnik.proto

package reminder

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/ysugimoto/grpc-graphql-gateway/graphql"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Reminder struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Moment               int64    `protobuf:"varint,6,opt,name=moment,proto3" json:"moment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reminder) Reset()         { *m = Reminder{} }
func (m *Reminder) String() string { return proto.CompactTextString(m) }
func (*Reminder) ProtoMessage()    {}
func (*Reminder) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{0}
}

func (m *Reminder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reminder.Unmarshal(m, b)
}
func (m *Reminder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reminder.Marshal(b, m, deterministic)
}
func (m *Reminder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reminder.Merge(m, src)
}
func (m *Reminder) XXX_Size() int {
	return xxx_messageInfo_Reminder.Size(m)
}
func (m *Reminder) XXX_DiscardUnknown() {
	xxx_messageInfo_Reminder.DiscardUnknown(m)
}

var xxx_messageInfo_Reminder proto.InternalMessageInfo

func (m *Reminder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reminder) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Reminder) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Reminder) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Reminder) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Reminder) GetMoment() int64 {
	if m != nil {
		return m.Moment
	}
	return 0
}

type CreateReminderReq struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateReminderReq) Reset()         { *m = CreateReminderReq{} }
func (m *CreateReminderReq) String() string { return proto.CompactTextString(m) }
func (*CreateReminderReq) ProtoMessage()    {}
func (*CreateReminderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{1}
}

func (m *CreateReminderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReminderReq.Unmarshal(m, b)
}
func (m *CreateReminderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReminderReq.Marshal(b, m, deterministic)
}
func (m *CreateReminderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReminderReq.Merge(m, src)
}
func (m *CreateReminderReq) XXX_Size() int {
	return xxx_messageInfo_CreateReminderReq.Size(m)
}
func (m *CreateReminderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReminderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReminderReq proto.InternalMessageInfo

func (m *CreateReminderReq) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type CreateReminderRes struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateReminderRes) Reset()         { *m = CreateReminderRes{} }
func (m *CreateReminderRes) String() string { return proto.CompactTextString(m) }
func (*CreateReminderRes) ProtoMessage()    {}
func (*CreateReminderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{2}
}

func (m *CreateReminderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReminderRes.Unmarshal(m, b)
}
func (m *CreateReminderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReminderRes.Marshal(b, m, deterministic)
}
func (m *CreateReminderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReminderRes.Merge(m, src)
}
func (m *CreateReminderRes) XXX_Size() int {
	return xxx_messageInfo_CreateReminderRes.Size(m)
}
func (m *CreateReminderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReminderRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReminderRes proto.InternalMessageInfo

func (m *CreateReminderRes) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type GetAllRemindersReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRemindersReq) Reset()         { *m = GetAllRemindersReq{} }
func (m *GetAllRemindersReq) String() string { return proto.CompactTextString(m) }
func (*GetAllRemindersReq) ProtoMessage()    {}
func (*GetAllRemindersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{3}
}

func (m *GetAllRemindersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRemindersReq.Unmarshal(m, b)
}
func (m *GetAllRemindersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRemindersReq.Marshal(b, m, deterministic)
}
func (m *GetAllRemindersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRemindersReq.Merge(m, src)
}
func (m *GetAllRemindersReq) XXX_Size() int {
	return xxx_messageInfo_GetAllRemindersReq.Size(m)
}
func (m *GetAllRemindersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRemindersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRemindersReq proto.InternalMessageInfo

type GetAllRemindersRes struct {
	Reminder             []*Reminder `protobuf:"bytes,1,rep,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAllRemindersRes) Reset()         { *m = GetAllRemindersRes{} }
func (m *GetAllRemindersRes) String() string { return proto.CompactTextString(m) }
func (*GetAllRemindersRes) ProtoMessage()    {}
func (*GetAllRemindersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{4}
}

func (m *GetAllRemindersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRemindersRes.Unmarshal(m, b)
}
func (m *GetAllRemindersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRemindersRes.Marshal(b, m, deterministic)
}
func (m *GetAllRemindersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRemindersRes.Merge(m, src)
}
func (m *GetAllRemindersRes) XXX_Size() int {
	return xxx_messageInfo_GetAllRemindersRes.Size(m)
}
func (m *GetAllRemindersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRemindersRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRemindersRes proto.InternalMessageInfo

func (m *GetAllRemindersRes) GetReminder() []*Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type GetReminderByIDReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReminderByIDReq) Reset()         { *m = GetReminderByIDReq{} }
func (m *GetReminderByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetReminderByIDReq) ProtoMessage()    {}
func (*GetReminderByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{5}
}

func (m *GetReminderByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReminderByIDReq.Unmarshal(m, b)
}
func (m *GetReminderByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReminderByIDReq.Marshal(b, m, deterministic)
}
func (m *GetReminderByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReminderByIDReq.Merge(m, src)
}
func (m *GetReminderByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetReminderByIDReq.Size(m)
}
func (m *GetReminderByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReminderByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReminderByIDReq proto.InternalMessageInfo

func (m *GetReminderByIDReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetReminderByIDRes struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetReminderByIDRes) Reset()         { *m = GetReminderByIDRes{} }
func (m *GetReminderByIDRes) String() string { return proto.CompactTextString(m) }
func (*GetReminderByIDRes) ProtoMessage()    {}
func (*GetReminderByIDRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{6}
}

func (m *GetReminderByIDRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReminderByIDRes.Unmarshal(m, b)
}
func (m *GetReminderByIDRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReminderByIDRes.Marshal(b, m, deterministic)
}
func (m *GetReminderByIDRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReminderByIDRes.Merge(m, src)
}
func (m *GetReminderByIDRes) XXX_Size() int {
	return xxx_messageInfo_GetReminderByIDRes.Size(m)
}
func (m *GetReminderByIDRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReminderByIDRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetReminderByIDRes proto.InternalMessageInfo

func (m *GetReminderByIDRes) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type UpdateReminderReq struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateReminderReq) Reset()         { *m = UpdateReminderReq{} }
func (m *UpdateReminderReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReminderReq) ProtoMessage()    {}
func (*UpdateReminderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{7}
}

func (m *UpdateReminderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReminderReq.Unmarshal(m, b)
}
func (m *UpdateReminderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReminderReq.Marshal(b, m, deterministic)
}
func (m *UpdateReminderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReminderReq.Merge(m, src)
}
func (m *UpdateReminderReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReminderReq.Size(m)
}
func (m *UpdateReminderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReminderReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReminderReq proto.InternalMessageInfo

func (m *UpdateReminderReq) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type UpdateReminderRes struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateReminderRes) Reset()         { *m = UpdateReminderRes{} }
func (m *UpdateReminderRes) String() string { return proto.CompactTextString(m) }
func (*UpdateReminderRes) ProtoMessage()    {}
func (*UpdateReminderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{8}
}

func (m *UpdateReminderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReminderRes.Unmarshal(m, b)
}
func (m *UpdateReminderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReminderRes.Marshal(b, m, deterministic)
}
func (m *UpdateReminderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReminderRes.Merge(m, src)
}
func (m *UpdateReminderRes) XXX_Size() int {
	return xxx_messageInfo_UpdateReminderRes.Size(m)
}
func (m *UpdateReminderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReminderRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReminderRes proto.InternalMessageInfo

func (m *UpdateReminderRes) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type DeleteReminderReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReminderReq) Reset()         { *m = DeleteReminderReq{} }
func (m *DeleteReminderReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReminderReq) ProtoMessage()    {}
func (*DeleteReminderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{9}
}

func (m *DeleteReminderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReminderReq.Unmarshal(m, b)
}
func (m *DeleteReminderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReminderReq.Marshal(b, m, deterministic)
}
func (m *DeleteReminderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReminderReq.Merge(m, src)
}
func (m *DeleteReminderReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReminderReq.Size(m)
}
func (m *DeleteReminderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReminderReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReminderReq proto.InternalMessageInfo

func (m *DeleteReminderReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteReminderRes struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReminderRes) Reset()         { *m = DeleteReminderRes{} }
func (m *DeleteReminderRes) String() string { return proto.CompactTextString(m) }
func (*DeleteReminderRes) ProtoMessage()    {}
func (*DeleteReminderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{10}
}

func (m *DeleteReminderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReminderRes.Unmarshal(m, b)
}
func (m *DeleteReminderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReminderRes.Marshal(b, m, deterministic)
}
func (m *DeleteReminderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReminderRes.Merge(m, src)
}
func (m *DeleteReminderRes) XXX_Size() int {
	return xxx_messageInfo_DeleteReminderRes.Size(m)
}
func (m *DeleteReminderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReminderRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReminderRes proto.InternalMessageInfo

func (m *DeleteReminderRes) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterType((*Reminder)(nil), "reminder.Reminder")
	proto.RegisterType((*CreateReminderReq)(nil), "reminder.CreateReminderReq")
	proto.RegisterType((*CreateReminderRes)(nil), "reminder.CreateReminderRes")
	proto.RegisterType((*GetAllRemindersReq)(nil), "reminder.GetAllRemindersReq")
	proto.RegisterType((*GetAllRemindersRes)(nil), "reminder.GetAllRemindersRes")
	proto.RegisterType((*GetReminderByIDReq)(nil), "reminder.GetReminderByIDReq")
	proto.RegisterType((*GetReminderByIDRes)(nil), "reminder.GetReminderByIDRes")
	proto.RegisterType((*UpdateReminderReq)(nil), "reminder.UpdateReminderReq")
	proto.RegisterType((*UpdateReminderRes)(nil), "reminder.UpdateReminderRes")
	proto.RegisterType((*DeleteReminderReq)(nil), "reminder.DeleteReminderReq")
	proto.RegisterType((*DeleteReminderRes)(nil), "reminder.DeleteReminderRes")
}

func init() { proto.RegisterFile("zeigarnik.proto", fileDescriptor_ddab59dbebc62572) }

var fileDescriptor_ddab59dbebc62572 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x93, 0x12, 0xc2, 0x14, 0x9c, 0xe6, 0xf2, 0x90, 0x35, 0x74, 0x51, 0x19, 0x84, 0x2a,
	0x44, 0xe3, 0x3e, 0xc4, 0xa6, 0xbb, 0xe2, 0x48, 0x88, 0xad, 0x11, 0x1f, 0x30, 0x64, 0xae, 0xdc,
	0x11, 0x8e, 0x27, 0xf1, 0x4c, 0x2b, 0x1e, 0xaa, 0x90, 0xd8, 0xc3, 0x86, 0xef, 0xe0, 0x07, 0xf2,
	0x1b, 0xfc, 0x02, 0x1f, 0x82, 0x3c, 0xf6, 0xb8, 0x99, 0xb8, 0x0a, 0x2a, 0x5d, 0xde, 0x7b, 0xce,
	0x9c, 0x73, 0x5f, 0x1a, 0x32, 0xf8, 0x8c, 0x22, 0x65, 0x45, 0x2e, 0x3e, 0x8c, 0x66, 0x85, 0xd4,
	0x12, 0xfa, 0x05, 0x4e, 0x45, 0xce, 0xb1, 0xa0, 0xf7, 0xd2, 0x82, 0xcd, 0x4e, 0xe7, 0x59, 0x05,
	0xd0, 0xed, 0x54, 0xca, 0x34, 0xc3, 0x88, 0xcd, 0x44, 0xc4, 0xf2, 0x5c, 0x6a, 0xa6, 0x85, 0xcc,
	0x55, 0x85, 0x86, 0x3f, 0x3c, 0xd2, 0x4f, 0xea, 0x97, 0xe0, 0x93, 0x8e, 0xe0, 0x81, 0xb7, 0xe3,
	0xed, 0xde, 0x49, 0x3a, 0x82, 0x43, 0x40, 0x6e, 0x4f, 0x0a, 0x64, 0x1a, 0x79, 0xd0, 0xd9, 0xf1,
	0x76, 0xbb, 0x89, 0x0d, 0x4b, 0x64, 0x8a, 0x4a, 0xb1, 0x14, 0x83, 0xae, 0xa1, 0xdb, 0xb0, 0xd4,
	0xd0, 0x32, 0xd8, 0xa8, 0x34, 0xb4, 0x84, 0x47, 0xa4, 0xa7, 0x34, 0xd3, 0x67, 0x2a, 0xb8, 0x65,
	0x72, 0x75, 0x54, 0xe6, 0xa7, 0x72, 0x8a, 0xb9, 0x0e, 0x7a, 0x46, 0xba, 0x8e, 0xc2, 0x98, 0x0c,
	0x63, 0x63, 0x62, 0xab, 0x4a, 0x70, 0x0e, 0x23, 0xd2, 0xb4, 0x67, 0xca, 0xdb, 0x3c, 0x84, 0x91,
	0x4d, 0x8c, 0x1a, 0x62, 0xc3, 0xb9, 0x4a, 0x44, 0x5d, 0x5b, 0xe4, 0x01, 0x81, 0xd7, 0xa8, 0x4f,
	0xb2, 0xcc, 0x62, 0x2a, 0xc1, 0x79, 0x38, 0xbe, 0x22, 0xbb, 0xaa, 0xdd, 0xfd, 0xa7, 0xf6, 0x53,
	0xa3, 0x62, 0x81, 0x57, 0x9f, 0xde, 0x8c, 0xcb, 0x36, 0x57, 0xe6, 0x5f, 0x7b, 0xb9, 0x2c, 0xf5,
	0x3f, 0xc3, 0x78, 0x37, 0xe3, 0x37, 0x9f, 0xe8, 0xaa, 0xc8, 0xf5, 0x2b, 0x79, 0x42, 0x86, 0x63,
	0xcc, 0xd0, 0xad, 0x64, 0xb5, 0xe9, 0xbd, 0x36, 0x49, 0x95, 0xf7, 0xc6, 0x4d, 0xb2, 0x62, 0xf6,
	0x13, 0x1b, 0x1e, 0xfe, 0xda, 0x20, 0x03, 0xcb, 0x7c, 0x8b, 0xc5, 0xb9, 0x98, 0x20, 0x7c, 0x25,
	0xbe, 0xbb, 0x7e, 0x78, 0x7c, 0x59, 0x57, 0xeb, 0xba, 0xe8, 0x1a, 0x50, 0x85, 0x47, 0x8b, 0x18,
	0xfa, 0x1e, 0xf8, 0x13, 0x07, 0xf9, 0xf6, 0xfb, 0xcf, 0xcf, 0x4e, 0x10, 0xde, 0x8d, 0xce, 0x0f,
	0x22, 0xfb, 0xf8, 0xb8, 0x69, 0x14, 0x3e, 0x92, 0xcd, 0xa5, 0xc5, 0xc1, 0xf6, 0xa5, 0x41, 0x7b,
	0xeb, 0x74, 0x1d, 0xaa, 0xc2, 0xbd, 0x45, 0x3c, 0x84, 0x41, 0xea, 0x02, 0xc6, 0xfe, 0x3e, 0x0c,
	0x97, 0xed, 0xa3, 0x2f, 0x82, 0x5f, 0xc0, 0x77, 0x8f, 0xf8, 0xee, 0xa2, 0x96, 0x7b, 0x6f, 0xdd,
	0x01, 0x5d, 0x03, 0xaa, 0xf0, 0xa4, 0xee, 0xfd, 0xcc, 0x41, 0x8c, 0xf9, 0x33, 0x4a, 0x5d, 0xf3,
	0x46, 0x46, 0xf0, 0x0b, 0x67, 0x12, 0xbe, 0xbb, 0xcd, 0xe5, 0x72, 0x5a, 0xc7, 0x40, 0xd7, 0x80,
	0x2a, 0x7c, 0xb1, 0x88, 0xb7, 0xc0, 0xe7, 0x4e, 0xbe, 0x9a, 0xc4, 0xf3, 0xf6, 0x24, 0xe8, 0xc3,
	0x45, 0x0c, 0xc4, 0xcf, 0xe4, 0x84, 0x65, 0xa7, 0x52, 0xe9, 0xe3, 0x97, 0xfb, 0xfb, 0x07, 0x5b,
	0xde, 0xfb, 0x9e, 0xf9, 0xf7, 0x8e, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x42, 0x86, 0x0d, 0x32,
	0x41, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReminderServiceClient is the client API for ReminderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReminderServiceClient interface {
	CreateReminder(ctx context.Context, in *CreateReminderReq, opts ...grpc.CallOption) (*CreateReminderRes, error)
	GetReminder(ctx context.Context, in *GetReminderByIDReq, opts ...grpc.CallOption) (*GetReminderByIDRes, error)
	UpdateReminder(ctx context.Context, in *UpdateReminderReq, opts ...grpc.CallOption) (*UpdateReminderRes, error)
	DeleteReminder(ctx context.Context, in *DeleteReminderReq, opts ...grpc.CallOption) (*DeleteReminderRes, error)
}

type reminderServiceClient struct {
	cc *grpc.ClientConn
}

func NewReminderServiceClient(cc *grpc.ClientConn) ReminderServiceClient {
	return &reminderServiceClient{cc}
}

func (c *reminderServiceClient) CreateReminder(ctx context.Context, in *CreateReminderReq, opts ...grpc.CallOption) (*CreateReminderRes, error) {
	out := new(CreateReminderRes)
	err := c.cc.Invoke(ctx, "/reminder.ReminderService/CreateReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) GetReminder(ctx context.Context, in *GetReminderByIDReq, opts ...grpc.CallOption) (*GetReminderByIDRes, error) {
	out := new(GetReminderByIDRes)
	err := c.cc.Invoke(ctx, "/reminder.ReminderService/GetReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) UpdateReminder(ctx context.Context, in *UpdateReminderReq, opts ...grpc.CallOption) (*UpdateReminderRes, error) {
	out := new(UpdateReminderRes)
	err := c.cc.Invoke(ctx, "/reminder.ReminderService/UpdateReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) DeleteReminder(ctx context.Context, in *DeleteReminderReq, opts ...grpc.CallOption) (*DeleteReminderRes, error) {
	out := new(DeleteReminderRes)
	err := c.cc.Invoke(ctx, "/reminder.ReminderService/DeleteReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReminderServiceServer is the server API for ReminderService service.
type ReminderServiceServer interface {
	CreateReminder(context.Context, *CreateReminderReq) (*CreateReminderRes, error)
	GetReminder(context.Context, *GetReminderByIDReq) (*GetReminderByIDRes, error)
	UpdateReminder(context.Context, *UpdateReminderReq) (*UpdateReminderRes, error)
	DeleteReminder(context.Context, *DeleteReminderReq) (*DeleteReminderRes, error)
}

// UnimplementedReminderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReminderServiceServer struct {
}

func (*UnimplementedReminderServiceServer) CreateReminder(ctx context.Context, req *CreateReminderReq) (*CreateReminderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReminder not implemented")
}
func (*UnimplementedReminderServiceServer) GetReminder(ctx context.Context, req *GetReminderByIDReq) (*GetReminderByIDRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReminder not implemented")
}
func (*UnimplementedReminderServiceServer) UpdateReminder(ctx context.Context, req *UpdateReminderReq) (*UpdateReminderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReminder not implemented")
}
func (*UnimplementedReminderServiceServer) DeleteReminder(ctx context.Context, req *DeleteReminderReq) (*DeleteReminderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReminder not implemented")
}

func RegisterReminderServiceServer(s *grpc.Server, srv ReminderServiceServer) {
	s.RegisterService(&_ReminderService_serviceDesc, srv)
}

func _ReminderService_CreateReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReminderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).CreateReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.ReminderService/CreateReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).CreateReminder(ctx, req.(*CreateReminderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_GetReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReminderByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).GetReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.ReminderService/GetReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).GetReminder(ctx, req.(*GetReminderByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_UpdateReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReminderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).UpdateReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.ReminderService/UpdateReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).UpdateReminder(ctx, req.(*UpdateReminderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_DeleteReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReminderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).DeleteReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.ReminderService/DeleteReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).DeleteReminder(ctx, req.(*DeleteReminderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReminderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reminder.ReminderService",
	HandlerType: (*ReminderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReminder",
			Handler:    _ReminderService_CreateReminder_Handler,
		},
		{
			MethodName: "GetReminder",
			Handler:    _ReminderService_GetReminder_Handler,
		},
		{
			MethodName: "UpdateReminder",
			Handler:    _ReminderService_UpdateReminder_Handler,
		},
		{
			MethodName: "DeleteReminder",
			Handler:    _ReminderService_DeleteReminder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zeigarnik.proto",
}
