// Code generated by sqlc. DO NOT EDIT.
// source: create_reminder.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const createReminder = `-- name: CreateReminder :one
insert into reminders (id, created, msg) values ($1, $2, $3) returning id, created, msg
`

type CreateReminderParams struct {
	ID      uuid.UUID `json:"id"`
	Created int32     `json:"created"`
	Msg     string    `json:"msg"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.queryRow(ctx, q.createReminderStmt, createReminder, arg.ID, arg.Created, arg.Msg)
	var i Reminder
	err := row.Scan(&i.ID, &i.Created, &i.Msg)
	return i, err
}
