// Code generated by sqlc. DO NOT EDIT.
// source: delete_reminder.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const deleteReminder = `-- name: DeleteReminder :one
delete from reminders where id = $1 returning id, created, msg
`

func (q *Queries) DeleteReminder(ctx context.Context, id uuid.UUID) (Reminder, error) {
	row := q.queryRow(ctx, q.deleteReminderStmt, deleteReminder, id)
	var i Reminder
	err := row.Scan(&i.ID, &i.Created, &i.Msg)
	return i, err
}
