// Code generated by sqlc. DO NOT EDIT.

package sql

import (
	"github.com/google/uuid"
)

type Reminder struct {
	ID      uuid.UUID `json:"id"`
	Created int32     `json:"created"`
	Msg     string    `json:"msg"`
}
