// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zeigarnik.proto

package reminder

import (
	context "context"
	fmt "fmt"
	_ "github.com/bold-commerce/protoc-gen-struct-transformer/options"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/ysugimoto/grpc-graphql-gateway/graphql"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReminderType int32

const (
	ReminderType_INVALID ReminderType = 0
	ReminderType_AT      ReminderType = 1
	ReminderType_AFTER   ReminderType = 2
)

var ReminderType_name = map[int32]string{
	0: "INVALID",
	1: "AT",
	2: "AFTER",
}

var ReminderType_value = map[string]int32{
	"INVALID": 0,
	"AT":      1,
	"AFTER":   2,
}

func (x ReminderType) String() string {
	return proto.EnumName(ReminderType_name, int32(x))
}

func (ReminderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{0}
}

type ReminderStatus int32

const (
	ReminderStatus_UNKNOWN ReminderStatus = 0
	ReminderStatus_CREATED ReminderStatus = 1
	ReminderStatus_QUEUED  ReminderStatus = 2
	ReminderStatus_FIRED   ReminderStatus = 3
	ReminderStatus_MISSED  ReminderStatus = 4
)

var ReminderStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "CREATED",
	2: "QUEUED",
	3: "FIRED",
	4: "MISSED",
}

var ReminderStatus_value = map[string]int32{
	"UNKNOWN": 0,
	"CREATED": 1,
	"QUEUED":  2,
	"FIRED":   3,
	"MISSED":  4,
}

func (x ReminderStatus) String() string {
	return proto.EnumName(ReminderStatus_name, int32(x))
}

func (ReminderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{1}
}

type Reminder struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64          `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Message              string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	To                   string         `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Status               ReminderStatus `protobuf:"varint,5,opt,name=status,proto3,enum=reminder.v1alpha1.ReminderStatus" json:"status,omitempty"`
	When                 int64          `protobuf:"varint,6,opt,name=when,proto3" json:"when,omitempty"`
	Type                 ReminderType   `protobuf:"varint,7,opt,name=type,proto3,enum=reminder.v1alpha1.ReminderType" json:"type,omitempty"`
	WarnAt               []int64        `protobuf:"varint,8,rep,packed,name=warnAt,proto3" json:"warnAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Reminder) Reset()         { *m = Reminder{} }
func (m *Reminder) String() string { return proto.CompactTextString(m) }
func (*Reminder) ProtoMessage()    {}
func (*Reminder) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{0}
}

func (m *Reminder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reminder.Unmarshal(m, b)
}
func (m *Reminder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reminder.Marshal(b, m, deterministic)
}
func (m *Reminder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reminder.Merge(m, src)
}
func (m *Reminder) XXX_Size() int {
	return xxx_messageInfo_Reminder.Size(m)
}
func (m *Reminder) XXX_DiscardUnknown() {
	xxx_messageInfo_Reminder.DiscardUnknown(m)
}

var xxx_messageInfo_Reminder proto.InternalMessageInfo

func (m *Reminder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reminder) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Reminder) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Reminder) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Reminder) GetStatus() ReminderStatus {
	if m != nil {
		return m.Status
	}
	return ReminderStatus_UNKNOWN
}

func (m *Reminder) GetWhen() int64 {
	if m != nil {
		return m.When
	}
	return 0
}

func (m *Reminder) GetType() ReminderType {
	if m != nil {
		return m.Type
	}
	return ReminderType_INVALID
}

func (m *Reminder) GetWarnAt() []int64 {
	if m != nil {
		return m.WarnAt
	}
	return nil
}

type ListRemindersReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRemindersReq) Reset()         { *m = ListRemindersReq{} }
func (m *ListRemindersReq) String() string { return proto.CompactTextString(m) }
func (*ListRemindersReq) ProtoMessage()    {}
func (*ListRemindersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{1}
}

func (m *ListRemindersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRemindersReq.Unmarshal(m, b)
}
func (m *ListRemindersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRemindersReq.Marshal(b, m, deterministic)
}
func (m *ListRemindersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRemindersReq.Merge(m, src)
}
func (m *ListRemindersReq) XXX_Size() int {
	return xxx_messageInfo_ListRemindersReq.Size(m)
}
func (m *ListRemindersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRemindersReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListRemindersReq proto.InternalMessageInfo

type ListRemindersRes struct {
	Reminders            []string `protobuf:"bytes,1,rep,name=reminders,proto3" json:"reminders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRemindersRes) Reset()         { *m = ListRemindersRes{} }
func (m *ListRemindersRes) String() string { return proto.CompactTextString(m) }
func (*ListRemindersRes) ProtoMessage()    {}
func (*ListRemindersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{2}
}

func (m *ListRemindersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRemindersRes.Unmarshal(m, b)
}
func (m *ListRemindersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRemindersRes.Marshal(b, m, deterministic)
}
func (m *ListRemindersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRemindersRes.Merge(m, src)
}
func (m *ListRemindersRes) XXX_Size() int {
	return xxx_messageInfo_ListRemindersRes.Size(m)
}
func (m *ListRemindersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRemindersRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListRemindersRes proto.InternalMessageInfo

func (m *ListRemindersRes) GetReminders() []string {
	if m != nil {
		return m.Reminders
	}
	return nil
}

type GetReminderByIDReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReminderByIDReq) Reset()         { *m = GetReminderByIDReq{} }
func (m *GetReminderByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetReminderByIDReq) ProtoMessage()    {}
func (*GetReminderByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{3}
}

func (m *GetReminderByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReminderByIDReq.Unmarshal(m, b)
}
func (m *GetReminderByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReminderByIDReq.Marshal(b, m, deterministic)
}
func (m *GetReminderByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReminderByIDReq.Merge(m, src)
}
func (m *GetReminderByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetReminderByIDReq.Size(m)
}
func (m *GetReminderByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReminderByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReminderByIDReq proto.InternalMessageInfo

func (m *GetReminderByIDReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetReminderByIDRes struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetReminderByIDRes) Reset()         { *m = GetReminderByIDRes{} }
func (m *GetReminderByIDRes) String() string { return proto.CompactTextString(m) }
func (*GetReminderByIDRes) ProtoMessage()    {}
func (*GetReminderByIDRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{4}
}

func (m *GetReminderByIDRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReminderByIDRes.Unmarshal(m, b)
}
func (m *GetReminderByIDRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReminderByIDRes.Marshal(b, m, deterministic)
}
func (m *GetReminderByIDRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReminderByIDRes.Merge(m, src)
}
func (m *GetReminderByIDRes) XXX_Size() int {
	return xxx_messageInfo_GetReminderByIDRes.Size(m)
}
func (m *GetReminderByIDRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReminderByIDRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetReminderByIDRes proto.InternalMessageInfo

func (m *GetReminderByIDRes) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type CreateReminderReq struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateReminderReq) Reset()         { *m = CreateReminderReq{} }
func (m *CreateReminderReq) String() string { return proto.CompactTextString(m) }
func (*CreateReminderReq) ProtoMessage()    {}
func (*CreateReminderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{5}
}

func (m *CreateReminderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReminderReq.Unmarshal(m, b)
}
func (m *CreateReminderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReminderReq.Marshal(b, m, deterministic)
}
func (m *CreateReminderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReminderReq.Merge(m, src)
}
func (m *CreateReminderReq) XXX_Size() int {
	return xxx_messageInfo_CreateReminderReq.Size(m)
}
func (m *CreateReminderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReminderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReminderReq proto.InternalMessageInfo

func (m *CreateReminderReq) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type CreateReminderRes struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateReminderRes) Reset()         { *m = CreateReminderRes{} }
func (m *CreateReminderRes) String() string { return proto.CompactTextString(m) }
func (*CreateReminderRes) ProtoMessage()    {}
func (*CreateReminderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{6}
}

func (m *CreateReminderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReminderRes.Unmarshal(m, b)
}
func (m *CreateReminderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReminderRes.Marshal(b, m, deterministic)
}
func (m *CreateReminderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReminderRes.Merge(m, src)
}
func (m *CreateReminderRes) XXX_Size() int {
	return xxx_messageInfo_CreateReminderRes.Size(m)
}
func (m *CreateReminderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReminderRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReminderRes proto.InternalMessageInfo

func (m *CreateReminderRes) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type UpdateReminderReq struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateReminderReq) Reset()         { *m = UpdateReminderReq{} }
func (m *UpdateReminderReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReminderReq) ProtoMessage()    {}
func (*UpdateReminderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{7}
}

func (m *UpdateReminderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReminderReq.Unmarshal(m, b)
}
func (m *UpdateReminderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReminderReq.Marshal(b, m, deterministic)
}
func (m *UpdateReminderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReminderReq.Merge(m, src)
}
func (m *UpdateReminderReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReminderReq.Size(m)
}
func (m *UpdateReminderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReminderReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReminderReq proto.InternalMessageInfo

func (m *UpdateReminderReq) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type UpdateReminderRes struct {
	Reminder             *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateReminderRes) Reset()         { *m = UpdateReminderRes{} }
func (m *UpdateReminderRes) String() string { return proto.CompactTextString(m) }
func (*UpdateReminderRes) ProtoMessage()    {}
func (*UpdateReminderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{8}
}

func (m *UpdateReminderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReminderRes.Unmarshal(m, b)
}
func (m *UpdateReminderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReminderRes.Marshal(b, m, deterministic)
}
func (m *UpdateReminderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReminderRes.Merge(m, src)
}
func (m *UpdateReminderRes) XXX_Size() int {
	return xxx_messageInfo_UpdateReminderRes.Size(m)
}
func (m *UpdateReminderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReminderRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReminderRes proto.InternalMessageInfo

func (m *UpdateReminderRes) GetReminder() *Reminder {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type DeleteReminderReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReminderReq) Reset()         { *m = DeleteReminderReq{} }
func (m *DeleteReminderReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReminderReq) ProtoMessage()    {}
func (*DeleteReminderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{9}
}

func (m *DeleteReminderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReminderReq.Unmarshal(m, b)
}
func (m *DeleteReminderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReminderReq.Marshal(b, m, deterministic)
}
func (m *DeleteReminderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReminderReq.Merge(m, src)
}
func (m *DeleteReminderReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReminderReq.Size(m)
}
func (m *DeleteReminderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReminderReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReminderReq proto.InternalMessageInfo

func (m *DeleteReminderReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteReminderRes struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReminderRes) Reset()         { *m = DeleteReminderRes{} }
func (m *DeleteReminderRes) String() string { return proto.CompactTextString(m) }
func (*DeleteReminderRes) ProtoMessage()    {}
func (*DeleteReminderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddab59dbebc62572, []int{10}
}

func (m *DeleteReminderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReminderRes.Unmarshal(m, b)
}
func (m *DeleteReminderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReminderRes.Marshal(b, m, deterministic)
}
func (m *DeleteReminderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReminderRes.Merge(m, src)
}
func (m *DeleteReminderRes) XXX_Size() int {
	return xxx_messageInfo_DeleteReminderRes.Size(m)
}
func (m *DeleteReminderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReminderRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReminderRes proto.InternalMessageInfo

func (m *DeleteReminderRes) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterEnum("reminder.v1alpha1.ReminderType", ReminderType_name, ReminderType_value)
	proto.RegisterEnum("reminder.v1alpha1.ReminderStatus", ReminderStatus_name, ReminderStatus_value)
	proto.RegisterType((*Reminder)(nil), "reminder.v1alpha1.Reminder")
	proto.RegisterType((*ListRemindersReq)(nil), "reminder.v1alpha1.ListRemindersReq")
	proto.RegisterType((*ListRemindersRes)(nil), "reminder.v1alpha1.ListRemindersRes")
	proto.RegisterType((*GetReminderByIDReq)(nil), "reminder.v1alpha1.GetReminderByIDReq")
	proto.RegisterType((*GetReminderByIDRes)(nil), "reminder.v1alpha1.GetReminderByIDRes")
	proto.RegisterType((*CreateReminderReq)(nil), "reminder.v1alpha1.CreateReminderReq")
	proto.RegisterType((*CreateReminderRes)(nil), "reminder.v1alpha1.CreateReminderRes")
	proto.RegisterType((*UpdateReminderReq)(nil), "reminder.v1alpha1.UpdateReminderReq")
	proto.RegisterType((*UpdateReminderRes)(nil), "reminder.v1alpha1.UpdateReminderRes")
	proto.RegisterType((*DeleteReminderReq)(nil), "reminder.v1alpha1.DeleteReminderReq")
	proto.RegisterType((*DeleteReminderRes)(nil), "reminder.v1alpha1.DeleteReminderRes")
}

func init() { proto.RegisterFile("zeigarnik.proto", fileDescriptor_ddab59dbebc62572) }

var fileDescriptor_ddab59dbebc62572 = []byte{
	// 706 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0xad, 0x9d, 0x34, 0x4d, 0xa6, 0xad, 0x6b, 0xdf, 0xa7, 0xf7, 0xe4, 0x67, 0x2a, 0x11, 0x4c,
	0x41, 0x51, 0x45, 0xe3, 0xa6, 0x15, 0x42, 0x94, 0x05, 0x4a, 0x63, 0x17, 0x45, 0x34, 0x41, 0x4c,
	0x13, 0x90, 0xd8, 0x99, 0x78, 0xe4, 0x58, 0x75, 0x6d, 0xc7, 0xe3, 0xb6, 0x2a, 0xa8, 0x1b, 0x96,
	0x95, 0x58, 0x00, 0x3b, 0x36, 0xfc, 0x47, 0x16, 0xec, 0xfa, 0x05, 0xfc, 0x01, 0xe2, 0x23, 0x58,
	0x22, 0x3b, 0xb1, 0xa9, 0xeb, 0xa8, 0x8a, 0xd4, 0xae, 0xec, 0x7b, 0xef, 0x99, 0x33, 0x67, 0xce,
	0xdc, 0x6b, 0xa3, 0xa5, 0x77, 0xc4, 0x32, 0x75, 0xdf, 0xb1, 0xf6, 0xab, 0x9e, 0xef, 0x06, 0x2e,
	0x08, 0x3e, 0x39, 0xb0, 0x1c, 0x83, 0xf8, 0xd5, 0xa3, 0x9a, 0x6e, 0x7b, 0x7d, 0xbd, 0x26, 0x2d,
	0x9a, 0xbe, 0xee, 0xf5, 0x07, 0xf6, 0x08, 0x21, 0x2d, 0x9b, 0xae, 0x6b, 0xda, 0x44, 0xd1, 0x3d,
	0x4b, 0xd1, 0x1d, 0xc7, 0x0d, 0xf4, 0xc0, 0x72, 0x1d, 0x3a, 0xae, 0xfe, 0xef, 0x7a, 0x51, 0x98,
	0x2d, 0xc9, 0x1f, 0x59, 0x54, 0xc4, 0x63, 0x76, 0xe0, 0x10, 0x6b, 0x19, 0x22, 0x53, 0x66, 0x2a,
	0x25, 0xcc, 0x5a, 0x06, 0x88, 0x68, 0xae, 0xe7, 0x13, 0x3d, 0x20, 0x86, 0xc8, 0x96, 0x99, 0x4a,
	0x0e, 0xc7, 0x61, 0x58, 0x39, 0x20, 0x94, 0xea, 0x26, 0x11, 0x73, 0x11, 0x3c, 0x0e, 0x43, 0x8e,
	0xc0, 0x15, 0xf3, 0x23, 0x8e, 0xc0, 0x85, 0xc7, 0xa8, 0x40, 0x03, 0x3d, 0x38, 0xa4, 0xe2, 0x6c,
	0x99, 0xa9, 0x70, 0x1b, 0x77, 0xaa, 0x99, 0xc3, 0x54, 0x63, 0x01, 0x7b, 0x11, 0x10, 0x8f, 0x17,
	0x00, 0xa0, 0xfc, 0x71, 0x9f, 0x38, 0x62, 0x21, 0xda, 0x3b, 0x7a, 0x87, 0x4d, 0x94, 0x0f, 0x4e,
	0x3c, 0x22, 0xce, 0x45, 0x64, 0xb7, 0xaf, 0x20, 0xeb, 0x9c, 0x78, 0x04, 0x47, 0x60, 0xf8, 0x0f,
	0x15, 0x8e, 0x75, 0xdf, 0xa9, 0x07, 0x62, 0xb1, 0x9c, 0xab, 0xe4, 0xf0, 0x38, 0xda, 0x12, 0x7e,
	0x7e, 0x67, 0x17, 0x63, 0x7c, 0xcb, 0x35, 0x88, 0x2d, 0x03, 0xe2, 0x77, 0x2d, 0x1a, 0xc4, 0x49,
	0x8a, 0xc9, 0x40, 0x5e, 0xcf, 0xe4, 0x28, 0x2c, 0xa3, 0x52, 0xbc, 0x35, 0x15, 0x99, 0x72, 0xae,
	0x52, 0xc2, 0x7f, 0x13, 0xf2, 0x0a, 0x82, 0x67, 0x24, 0x59, 0xb0, 0x7d, 0xd2, 0x54, 0x31, 0x19,
	0x5c, 0xb6, 0x57, 0x6e, 0x4d, 0x40, 0x51, 0x78, 0x84, 0x8a, 0x31, 0x51, 0x84, 0x9d, 0xdf, 0xb8,
	0x75, 0xc5, 0x29, 0x71, 0x02, 0x96, 0x77, 0x91, 0xd0, 0x88, 0xae, 0x27, 0xa9, 0x91, 0xc1, 0x8d,
	0xb2, 0x5d, 0x4f, 0x5b, 0xd7, 0x33, 0x6e, 0x50, 0xdb, 0x65, 0xb6, 0x6b, 0x68, 0xbb, 0x8b, 0x04,
	0x95, 0xd8, 0x24, 0xad, 0xed, 0xf2, 0x5d, 0xad, 0x65, 0x41, 0x34, 0x9c, 0x02, 0x23, 0x4a, 0x8e,
	0x90, 0x45, 0x1c, 0x87, 0xab, 0x55, 0xb4, 0x70, 0xb1, 0x0f, 0x61, 0x1e, 0xcd, 0x35, 0xdb, 0xaf,
	0xea, 0xbb, 0x4d, 0x95, 0x9f, 0x81, 0x02, 0x62, 0xeb, 0x1d, 0x9e, 0x81, 0x12, 0x9a, 0xad, 0xef,
	0x74, 0x34, 0xcc, 0xb3, 0xab, 0x2d, 0xc4, 0xa5, 0x87, 0x20, 0x5c, 0xd1, 0x6d, 0x3f, 0x6f, 0xbf,
	0x78, 0xdd, 0xe6, 0x67, 0xc2, 0xa0, 0x81, 0xb5, 0x7a, 0x47, 0x53, 0x79, 0x06, 0x10, 0x2a, 0xbc,
	0xec, 0x6a, 0x5d, 0x4d, 0xe5, 0xd9, 0x90, 0x62, 0xa7, 0x89, 0x35, 0x95, 0xcf, 0x85, 0xe9, 0x56,
	0x73, 0x6f, 0x4f, 0x53, 0xf9, 0xfc, 0xc6, 0xef, 0x3c, 0x5a, 0x4a, 0xf8, 0x88, 0x7f, 0x64, 0xf5,
	0x08, 0x7c, 0x62, 0x10, 0x97, 0xbe, 0x51, 0x58, 0x99, 0x60, 0x50, 0xa6, 0x85, 0xa4, 0x69, 0x50,
	0x54, 0xde, 0x1c, 0x36, 0xa0, 0xc8, 0x00, 0xd7, 0x4b, 0x55, 0x3e, 0xfc, 0xf8, 0xf5, 0x85, 0x15,
	0xe5, 0x05, 0xe5, 0xa8, 0xa6, 0xc4, 0x2c, 0x5b, 0x89, 0xf5, 0x70, 0xc6, 0xa0, 0xf9, 0x0b, 0x23,
	0x00, 0xf7, 0x26, 0x6c, 0x95, 0x1d, 0x24, 0x69, 0x2a, 0x18, 0x95, 0xd7, 0x86, 0x0d, 0x01, 0x96,
	0xcc, 0x74, 0x21, 0x52, 0xf4, 0x0f, 0x08, 0x17, 0x15, 0x29, 0xef, 0x2d, 0xe3, 0x14, 0xbe, 0x31,
	0x88, 0x4b, 0xb7, 0xd5, 0x44, 0x83, 0x32, 0x7d, 0x2c, 0x4d, 0x83, 0xa2, 0x72, 0x7d, 0x6c, 0xd0,
	0x61, 0xaa, 0x12, 0xc9, 0xb9, 0x2f, 0x49, 0x69, 0x39, 0x09, 0x9f, 0x65, 0x9c, 0xa6, 0xed, 0xe2,
	0xd2, 0x5d, 0x38, 0x51, 0x61, 0xa6, 0x9b, 0xa5, 0x69, 0x50, 0x54, 0x7e, 0x30, 0x6c, 0xf0, 0xc0,
	0x19, 0xa9, 0xfc, 0xc8, 0xae, 0xd5, 0xac, 0x5d, 0xd2, 0xbf, 0xc3, 0x06, 0x20, 0xce, 0x76, 0x7b,
	0xba, 0xdd, 0x77, 0x69, 0xb0, 0xf5, 0x70, 0x7d, 0xbd, 0xc6, 0x33, 0xdb, 0x4f, 0xcf, 0xce, 0x59,
	0xc1, 0xdb, 0x37, 0x15, 0x3a, 0xb0, 0x95, 0x83, 0xf0, 0x9b, 0x4a, 0xab, 0xa6, 0xfb, 0xf9, 0x9c,
	0xcd, 0xd1, 0x81, 0xfd, 0x75, 0xf4, 0x78, 0x23, 0x25, 0x54, 0xb1, 0x9c, 0x27, 0x71, 0xe6, 0x6d,
	0x21, 0xfa, 0x31, 0x6d, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x1c, 0x36, 0x5e, 0x06, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReminderServiceClient is the client API for ReminderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReminderServiceClient interface {
	CreateReminder(ctx context.Context, in *CreateReminderReq, opts ...grpc.CallOption) (*CreateReminderRes, error)
	GetReminder(ctx context.Context, in *GetReminderByIDReq, opts ...grpc.CallOption) (*GetReminderByIDRes, error)
	UpdateReminder(ctx context.Context, in *UpdateReminderReq, opts ...grpc.CallOption) (*UpdateReminderRes, error)
	DeleteReminder(ctx context.Context, in *DeleteReminderReq, opts ...grpc.CallOption) (*DeleteReminderRes, error)
}

type reminderServiceClient struct {
	cc *grpc.ClientConn
}

func NewReminderServiceClient(cc *grpc.ClientConn) ReminderServiceClient {
	return &reminderServiceClient{cc}
}

func (c *reminderServiceClient) CreateReminder(ctx context.Context, in *CreateReminderReq, opts ...grpc.CallOption) (*CreateReminderRes, error) {
	out := new(CreateReminderRes)
	err := c.cc.Invoke(ctx, "/reminder.v1alpha1.ReminderService/CreateReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) GetReminder(ctx context.Context, in *GetReminderByIDReq, opts ...grpc.CallOption) (*GetReminderByIDRes, error) {
	out := new(GetReminderByIDRes)
	err := c.cc.Invoke(ctx, "/reminder.v1alpha1.ReminderService/GetReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) UpdateReminder(ctx context.Context, in *UpdateReminderReq, opts ...grpc.CallOption) (*UpdateReminderRes, error) {
	out := new(UpdateReminderRes)
	err := c.cc.Invoke(ctx, "/reminder.v1alpha1.ReminderService/UpdateReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) DeleteReminder(ctx context.Context, in *DeleteReminderReq, opts ...grpc.CallOption) (*DeleteReminderRes, error) {
	out := new(DeleteReminderRes)
	err := c.cc.Invoke(ctx, "/reminder.v1alpha1.ReminderService/DeleteReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReminderServiceServer is the server API for ReminderService service.
type ReminderServiceServer interface {
	CreateReminder(context.Context, *CreateReminderReq) (*CreateReminderRes, error)
	GetReminder(context.Context, *GetReminderByIDReq) (*GetReminderByIDRes, error)
	UpdateReminder(context.Context, *UpdateReminderReq) (*UpdateReminderRes, error)
	DeleteReminder(context.Context, *DeleteReminderReq) (*DeleteReminderRes, error)
}

// UnimplementedReminderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReminderServiceServer struct {
}

func (*UnimplementedReminderServiceServer) CreateReminder(ctx context.Context, req *CreateReminderReq) (*CreateReminderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReminder not implemented")
}
func (*UnimplementedReminderServiceServer) GetReminder(ctx context.Context, req *GetReminderByIDReq) (*GetReminderByIDRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReminder not implemented")
}
func (*UnimplementedReminderServiceServer) UpdateReminder(ctx context.Context, req *UpdateReminderReq) (*UpdateReminderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReminder not implemented")
}
func (*UnimplementedReminderServiceServer) DeleteReminder(ctx context.Context, req *DeleteReminderReq) (*DeleteReminderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReminder not implemented")
}

func RegisterReminderServiceServer(s *grpc.Server, srv ReminderServiceServer) {
	s.RegisterService(&_ReminderService_serviceDesc, srv)
}

func _ReminderService_CreateReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReminderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).CreateReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.v1alpha1.ReminderService/CreateReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).CreateReminder(ctx, req.(*CreateReminderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_GetReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReminderByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).GetReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.v1alpha1.ReminderService/GetReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).GetReminder(ctx, req.(*GetReminderByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_UpdateReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReminderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).UpdateReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.v1alpha1.ReminderService/UpdateReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).UpdateReminder(ctx, req.(*UpdateReminderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_DeleteReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReminderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).DeleteReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.v1alpha1.ReminderService/DeleteReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).DeleteReminder(ctx, req.(*DeleteReminderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReminderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reminder.v1alpha1.ReminderService",
	HandlerType: (*ReminderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReminder",
			Handler:    _ReminderService_CreateReminder_Handler,
		},
		{
			MethodName: "GetReminder",
			Handler:    _ReminderService_GetReminder_Handler,
		},
		{
			MethodName: "UpdateReminder",
			Handler:    _ReminderService_UpdateReminder_Handler,
		},
		{
			MethodName: "DeleteReminder",
			Handler:    _ReminderService_DeleteReminder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zeigarnik.proto",
}
