// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: zeigarnik.proto

package reminder

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/ysugimoto/grpc-graphql-gateway/graphql"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReminderType int32

const (
	ReminderType_INVALID ReminderType = 0
	ReminderType_AT      ReminderType = 1
	ReminderType_AFTER   ReminderType = 2
)

// Enum value maps for ReminderType.
var (
	ReminderType_name = map[int32]string{
		0: "INVALID",
		1: "AT",
		2: "AFTER",
	}
	ReminderType_value = map[string]int32{
		"INVALID": 0,
		"AT":      1,
		"AFTER":   2,
	}
)

func (x ReminderType) Enum() *ReminderType {
	p := new(ReminderType)
	*p = x
	return p
}

func (x ReminderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReminderType) Descriptor() protoreflect.EnumDescriptor {
	return file_zeigarnik_proto_enumTypes[0].Descriptor()
}

func (ReminderType) Type() protoreflect.EnumType {
	return &file_zeigarnik_proto_enumTypes[0]
}

func (x ReminderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReminderType.Descriptor instead.
func (ReminderType) EnumDescriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{0}
}

type ReminderStatus int32

const (
	ReminderStatus_UNKNOWN ReminderStatus = 0
	ReminderStatus_CREATED ReminderStatus = 1
	ReminderStatus_QUEUED  ReminderStatus = 2
	ReminderStatus_FIRED   ReminderStatus = 3
	ReminderStatus_MISSED  ReminderStatus = 4
)

// Enum value maps for ReminderStatus.
var (
	ReminderStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATED",
		2: "QUEUED",
		3: "FIRED",
		4: "MISSED",
	}
	ReminderStatus_value = map[string]int32{
		"UNKNOWN": 0,
		"CREATED": 1,
		"QUEUED":  2,
		"FIRED":   3,
		"MISSED":  4,
	}
)

func (x ReminderStatus) Enum() *ReminderStatus {
	p := new(ReminderStatus)
	*p = x
	return p
}

func (x ReminderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReminderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zeigarnik_proto_enumTypes[1].Descriptor()
}

func (ReminderStatus) Type() protoreflect.EnumType {
	return &file_zeigarnik_proto_enumTypes[1]
}

func (x ReminderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReminderStatus.Descriptor instead.
func (ReminderStatus) EnumDescriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{1}
}

type Reminder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created int64          `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Message string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	To      string         `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Status  ReminderStatus `protobuf:"varint,5,opt,name=status,proto3,enum=reminder.v1alpha1.ReminderStatus" json:"status,omitempty"`
	When    int64          `protobuf:"varint,6,opt,name=when,proto3" json:"when,omitempty"`
	Type    ReminderType   `protobuf:"varint,7,opt,name=type,proto3,enum=reminder.v1alpha1.ReminderType" json:"type,omitempty"`
	WarnAt  []int64        `protobuf:"varint,8,rep,packed,name=warnAt,proto3" json:"warnAt,omitempty"`
}

func (x *Reminder) Reset() {
	*x = Reminder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reminder) ProtoMessage() {}

func (x *Reminder) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reminder.ProtoReflect.Descriptor instead.
func (*Reminder) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{0}
}

func (x *Reminder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reminder) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Reminder) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Reminder) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Reminder) GetStatus() ReminderStatus {
	if x != nil {
		return x.Status
	}
	return ReminderStatus_UNKNOWN
}

func (x *Reminder) GetWhen() int64 {
	if x != nil {
		return x.When
	}
	return 0
}

func (x *Reminder) GetType() ReminderType {
	if x != nil {
		return x.Type
	}
	return ReminderType_INVALID
}

func (x *Reminder) GetWarnAt() []int64 {
	if x != nil {
		return x.WarnAt
	}
	return nil
}

type ListRemindersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRemindersReq) Reset() {
	*x = ListRemindersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRemindersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemindersReq) ProtoMessage() {}

func (x *ListRemindersReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemindersReq.ProtoReflect.Descriptor instead.
func (*ListRemindersReq) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{1}
}

type ListRemindersRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminders []string `protobuf:"bytes,1,rep,name=reminders,proto3" json:"reminders,omitempty"`
}

func (x *ListRemindersRes) Reset() {
	*x = ListRemindersRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRemindersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemindersRes) ProtoMessage() {}

func (x *ListRemindersRes) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemindersRes.ProtoReflect.Descriptor instead.
func (*ListRemindersRes) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{2}
}

func (x *ListRemindersRes) GetReminders() []string {
	if x != nil {
		return x.Reminders
	}
	return nil
}

type GetReminderByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetReminderByIDReq) Reset() {
	*x = GetReminderByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReminderByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderByIDReq) ProtoMessage() {}

func (x *GetReminderByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderByIDReq.ProtoReflect.Descriptor instead.
func (*GetReminderByIDReq) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{3}
}

func (x *GetReminderByIDReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReminderByIDRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminder *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
}

func (x *GetReminderByIDRes) Reset() {
	*x = GetReminderByIDRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReminderByIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderByIDRes) ProtoMessage() {}

func (x *GetReminderByIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderByIDRes.ProtoReflect.Descriptor instead.
func (*GetReminderByIDRes) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{4}
}

func (x *GetReminderByIDRes) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type CreateReminderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminder *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
}

func (x *CreateReminderReq) Reset() {
	*x = CreateReminderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReminderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderReq) ProtoMessage() {}

func (x *CreateReminderReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderReq.ProtoReflect.Descriptor instead.
func (*CreateReminderReq) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReminderReq) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type CreateReminderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminder *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
}

func (x *CreateReminderRes) Reset() {
	*x = CreateReminderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReminderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderRes) ProtoMessage() {}

func (x *CreateReminderRes) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderRes.ProtoReflect.Descriptor instead.
func (*CreateReminderRes) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{6}
}

func (x *CreateReminderRes) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type UpdateReminderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminder *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
}

func (x *UpdateReminderReq) Reset() {
	*x = UpdateReminderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReminderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReminderReq) ProtoMessage() {}

func (x *UpdateReminderReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReminderReq.ProtoReflect.Descriptor instead.
func (*UpdateReminderReq) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateReminderReq) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type UpdateReminderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminder *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
}

func (x *UpdateReminderRes) Reset() {
	*x = UpdateReminderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReminderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReminderRes) ProtoMessage() {}

func (x *UpdateReminderRes) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReminderRes.ProtoReflect.Descriptor instead.
func (*UpdateReminderRes) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateReminderRes) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type DeleteReminderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteReminderReq) Reset() {
	*x = DeleteReminderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReminderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReminderReq) ProtoMessage() {}

func (x *DeleteReminderReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReminderReq.ProtoReflect.Descriptor instead.
func (*DeleteReminderReq) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteReminderReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReminderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteReminderRes) Reset() {
	*x = DeleteReminderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeigarnik_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReminderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReminderRes) ProtoMessage() {}

func (x *DeleteReminderRes) ProtoReflect() protoreflect.Message {
	mi := &file_zeigarnik_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReminderRes.ProtoReflect.Descriptor instead.
func (*DeleteReminderRes) Descriptor() ([]byte, []int) {
	return file_zeigarnik_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteReminderRes) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_zeigarnik_proto protoreflect.FileDescriptor

var file_zeigarnik_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x7a, 0x65, 0x69, 0x67, 0x61, 0x72, 0x6e, 0x69, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x1a, 0x0d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xfa, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x77, 0x68, 0x65,
	0x6e, 0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x61, 0x72, 0x6e, 0x41, 0x74,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x77, 0x61, 0x72, 0x6e, 0x41, 0x74, 0x22, 0x12,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x22, 0x30, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x12, 0x37, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x37,
	0x0a, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x08, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x08,
	0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x65,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x2a, 0x2e, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x41, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x46,
	0x54, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x4d, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x46, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x49, 0x53, 0x53,
	0x45, 0x44, 0x10, 0x04, 0x32, 0xf8, 0x04, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x91, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x72, 0x65,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x24, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x33, 0xba, 0x43, 0x12, 0x08, 0x01, 0x12, 0x0e,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x18, 0x22, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x3a, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x8a, 0x01, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x25, 0x2e, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x22, 0x2d, 0xba, 0x43, 0x11, 0x12,
	0x0f, 0x67, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x9f, 0x01, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x24, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x41, 0xba, 0x43, 0x12, 0x08, 0x01, 0x12,
	0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x26, 0x1a, 0x1a, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x2f, 0x7b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x69, 0x64,
	0x7d, 0x3a, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x8a, 0x01, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x24,
	0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x2c, 0xba, 0x43, 0x10, 0x12,
	0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x2a, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x1a, 0x15, 0xba, 0x43, 0x12, 0x0a, 0x0e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x68, 0x6f, 0x73, 0x74, 0x3a, 0x35, 0x30, 0x30, 0x31, 0x10, 0x01, 0x42,
	0x1c, 0x5a, 0x1a, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x3b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zeigarnik_proto_rawDescOnce sync.Once
	file_zeigarnik_proto_rawDescData = file_zeigarnik_proto_rawDesc
)

func file_zeigarnik_proto_rawDescGZIP() []byte {
	file_zeigarnik_proto_rawDescOnce.Do(func() {
		file_zeigarnik_proto_rawDescData = protoimpl.X.CompressGZIP(file_zeigarnik_proto_rawDescData)
	})
	return file_zeigarnik_proto_rawDescData
}

var file_zeigarnik_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_zeigarnik_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_zeigarnik_proto_goTypes = []interface{}{
	(ReminderType)(0),          // 0: reminder.v1alpha1.ReminderType
	(ReminderStatus)(0),        // 1: reminder.v1alpha1.ReminderStatus
	(*Reminder)(nil),           // 2: reminder.v1alpha1.Reminder
	(*ListRemindersReq)(nil),   // 3: reminder.v1alpha1.ListRemindersReq
	(*ListRemindersRes)(nil),   // 4: reminder.v1alpha1.ListRemindersRes
	(*GetReminderByIDReq)(nil), // 5: reminder.v1alpha1.GetReminderByIDReq
	(*GetReminderByIDRes)(nil), // 6: reminder.v1alpha1.GetReminderByIDRes
	(*CreateReminderReq)(nil),  // 7: reminder.v1alpha1.CreateReminderReq
	(*CreateReminderRes)(nil),  // 8: reminder.v1alpha1.CreateReminderRes
	(*UpdateReminderReq)(nil),  // 9: reminder.v1alpha1.UpdateReminderReq
	(*UpdateReminderRes)(nil),  // 10: reminder.v1alpha1.UpdateReminderRes
	(*DeleteReminderReq)(nil),  // 11: reminder.v1alpha1.DeleteReminderReq
	(*DeleteReminderRes)(nil),  // 12: reminder.v1alpha1.DeleteReminderRes
}
var file_zeigarnik_proto_depIdxs = []int32{
	1,  // 0: reminder.v1alpha1.Reminder.status:type_name -> reminder.v1alpha1.ReminderStatus
	0,  // 1: reminder.v1alpha1.Reminder.type:type_name -> reminder.v1alpha1.ReminderType
	2,  // 2: reminder.v1alpha1.GetReminderByIDRes.reminder:type_name -> reminder.v1alpha1.Reminder
	2,  // 3: reminder.v1alpha1.CreateReminderReq.reminder:type_name -> reminder.v1alpha1.Reminder
	2,  // 4: reminder.v1alpha1.CreateReminderRes.reminder:type_name -> reminder.v1alpha1.Reminder
	2,  // 5: reminder.v1alpha1.UpdateReminderReq.reminder:type_name -> reminder.v1alpha1.Reminder
	2,  // 6: reminder.v1alpha1.UpdateReminderRes.reminder:type_name -> reminder.v1alpha1.Reminder
	7,  // 7: reminder.v1alpha1.ReminderService.CreateReminder:input_type -> reminder.v1alpha1.CreateReminderReq
	5,  // 8: reminder.v1alpha1.ReminderService.GetReminder:input_type -> reminder.v1alpha1.GetReminderByIDReq
	9,  // 9: reminder.v1alpha1.ReminderService.UpdateReminder:input_type -> reminder.v1alpha1.UpdateReminderReq
	11, // 10: reminder.v1alpha1.ReminderService.DeleteReminder:input_type -> reminder.v1alpha1.DeleteReminderReq
	8,  // 11: reminder.v1alpha1.ReminderService.CreateReminder:output_type -> reminder.v1alpha1.CreateReminderRes
	6,  // 12: reminder.v1alpha1.ReminderService.GetReminder:output_type -> reminder.v1alpha1.GetReminderByIDRes
	10, // 13: reminder.v1alpha1.ReminderService.UpdateReminder:output_type -> reminder.v1alpha1.UpdateReminderRes
	12, // 14: reminder.v1alpha1.ReminderService.DeleteReminder:output_type -> reminder.v1alpha1.DeleteReminderRes
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_zeigarnik_proto_init() }
func file_zeigarnik_proto_init() {
	if File_zeigarnik_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zeigarnik_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reminder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRemindersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRemindersRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReminderByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReminderByIDRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReminderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReminderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReminderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReminderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReminderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeigarnik_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReminderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zeigarnik_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zeigarnik_proto_goTypes,
		DependencyIndexes: file_zeigarnik_proto_depIdxs,
		EnumInfos:         file_zeigarnik_proto_enumTypes,
		MessageInfos:      file_zeigarnik_proto_msgTypes,
	}.Build()
	File_zeigarnik_proto = out.File
	file_zeigarnik_proto_rawDesc = nil
	file_zeigarnik_proto_goTypes = nil
	file_zeigarnik_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReminderServiceClient is the client API for ReminderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReminderServiceClient interface {
	CreateReminder(ctx context.Context, in *CreateReminderReq, opts ...grpc.CallOption) (*CreateReminderRes, error)
	GetReminder(ctx context.Context, in *GetReminderByIDReq, opts ...grpc.CallOption) (*GetReminderByIDRes, error)
	UpdateReminder(ctx context.Context, in *UpdateReminderReq, opts ...grpc.CallOption) (*UpdateReminderRes, error)
	DeleteReminder(ctx context.Context, in *DeleteReminderReq, opts ...grpc.CallOption) (*DeleteReminderRes, error)
}

type reminderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReminderServiceClient(cc grpc.ClientConnInterface) ReminderServiceClient {
	return &reminderServiceClient{cc}
}

func (c *reminderServiceClient) CreateReminder(ctx context.Context, in *CreateReminderReq, opts ...grpc.CallOption) (*CreateReminderRes, error) {
	out := new(CreateReminderRes)
	err := c.cc.Invoke(ctx, "/reminder.v1alpha1.ReminderService/CreateReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) GetReminder(ctx context.Context, in *GetReminderByIDReq, opts ...grpc.CallOption) (*GetReminderByIDRes, error) {
	out := new(GetReminderByIDRes)
	err := c.cc.Invoke(ctx, "/reminder.v1alpha1.ReminderService/GetReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) UpdateReminder(ctx context.Context, in *UpdateReminderReq, opts ...grpc.CallOption) (*UpdateReminderRes, error) {
	out := new(UpdateReminderRes)
	err := c.cc.Invoke(ctx, "/reminder.v1alpha1.ReminderService/UpdateReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reminderServiceClient) DeleteReminder(ctx context.Context, in *DeleteReminderReq, opts ...grpc.CallOption) (*DeleteReminderRes, error) {
	out := new(DeleteReminderRes)
	err := c.cc.Invoke(ctx, "/reminder.v1alpha1.ReminderService/DeleteReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReminderServiceServer is the server API for ReminderService service.
type ReminderServiceServer interface {
	CreateReminder(context.Context, *CreateReminderReq) (*CreateReminderRes, error)
	GetReminder(context.Context, *GetReminderByIDReq) (*GetReminderByIDRes, error)
	UpdateReminder(context.Context, *UpdateReminderReq) (*UpdateReminderRes, error)
	DeleteReminder(context.Context, *DeleteReminderReq) (*DeleteReminderRes, error)
}

// UnimplementedReminderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReminderServiceServer struct {
}

func (*UnimplementedReminderServiceServer) CreateReminder(context.Context, *CreateReminderReq) (*CreateReminderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReminder not implemented")
}
func (*UnimplementedReminderServiceServer) GetReminder(context.Context, *GetReminderByIDReq) (*GetReminderByIDRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReminder not implemented")
}
func (*UnimplementedReminderServiceServer) UpdateReminder(context.Context, *UpdateReminderReq) (*UpdateReminderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReminder not implemented")
}
func (*UnimplementedReminderServiceServer) DeleteReminder(context.Context, *DeleteReminderReq) (*DeleteReminderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReminder not implemented")
}

func RegisterReminderServiceServer(s *grpc.Server, srv ReminderServiceServer) {
	s.RegisterService(&_ReminderService_serviceDesc, srv)
}

func _ReminderService_CreateReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReminderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).CreateReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.v1alpha1.ReminderService/CreateReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).CreateReminder(ctx, req.(*CreateReminderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_GetReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReminderByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).GetReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.v1alpha1.ReminderService/GetReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).GetReminder(ctx, req.(*GetReminderByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_UpdateReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReminderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).UpdateReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.v1alpha1.ReminderService/UpdateReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).UpdateReminder(ctx, req.(*UpdateReminderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReminderService_DeleteReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReminderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReminderServiceServer).DeleteReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminder.v1alpha1.ReminderService/DeleteReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReminderServiceServer).DeleteReminder(ctx, req.(*DeleteReminderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReminderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reminder.v1alpha1.ReminderService",
	HandlerType: (*ReminderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReminder",
			Handler:    _ReminderService_CreateReminder_Handler,
		},
		{
			MethodName: "GetReminder",
			Handler:    _ReminderService_GetReminder_Handler,
		},
		{
			MethodName: "UpdateReminder",
			Handler:    _ReminderService_UpdateReminder_Handler,
		},
		{
			MethodName: "DeleteReminder",
			Handler:    _ReminderService_DeleteReminder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zeigarnik.proto",
}
